"""empty message

Revision ID: 64702ea1834d
Revises: 06614ec763fe
Create Date: 2019-04-19 03:56:38.990243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64702ea1834d'
down_revision = '06614ec763fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_genre_id', 'application', 'genre', ['genre_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_type_id', 'application', 'application_type', ['type_id'], ['id'], use_alter=True)
    op.add_column('session', sa.Column('status', sa.String(length=25), nullable=False))
    op.create_foreign_key('fk_app_id', 'session', 'application', ['app_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_questionnaire_id', 'session', 'questionnaire', ['questionnaire_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questionnaire_id', 'session', type_='foreignkey')
    op.drop_constraint('fk_app_id', 'session', type_='foreignkey')
    op.drop_column('session', 'status')
    op.drop_constraint('fk_type_id', 'application', type_='foreignkey')
    op.drop_constraint('fk_genre_id', 'application', type_='foreignkey')
    # ### end Alembic commands ###
