"""empty message

Revision ID: 6d973c15bfc3
Revises: 7fbc96b0d7b1
Create Date: 2019-04-15 17:52:44.231615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d973c15bfc3'
down_revision = '7fbc96b0d7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('app_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_genre_id', 'application', 'genre', ['genre_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_app_type_id', 'application', 'application_type', ['app_type_id'], ['id'], use_alter=True)
    op.drop_column('application', 'type_id')
    op.add_column('application_type', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('application_type', sa.Column('display_name_full', sa.String(length=250), nullable=False))
    op.add_column('genre', sa.Column('display_name', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genre', 'display_name')
    op.drop_column('application_type', 'display_name_full')
    op.drop_column('application_type', 'display_name')
    op.add_column('application', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint('fk_app_type_id', 'application', type_='foreignkey')
    op.drop_constraint('fk_genre_id', 'application', type_='foreignkey')
    op.drop_column('application', 'app_type_id')
    # ### end Alembic commands ###
