"""empty message

Revision ID: 89ee48680e79
Revises: cb018c771a53
Create Date: 2019-04-16 04:22:10.614121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ee48680e79'
down_revision = 'cb018c771a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_type_id', 'application', 'application_type', ['type_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_genre_id', 'application', 'genre', ['genre_id'], ['id'], use_alter=True)
    op.alter_column('questionnaire', 'post',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('questionnaire', 'session_id')
    op.create_foreign_key('fk_app_id', 'session', 'application', ['app_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_questionnaire_id', 'session', 'questionnaire', ['questionnaire_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questionnaire_id', 'session', type_='foreignkey')
    op.drop_constraint('fk_app_id', 'session', type_='foreignkey')
    op.add_column('questionnaire', sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('questionnaire', 'post',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_constraint('fk_genre_id', 'application', type_='foreignkey')
    op.drop_constraint('fk_type_id', 'application', type_='foreignkey')
    # ### end Alembic commands ###
