"""empty message

Revision ID: 926a10218c82
Revises: e8e7340162d7
Create Date: 2019-04-24 17:38:12.147730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926a10218c82'
down_revision = 'e8e7340162d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_type_id', 'application', 'application_type', ['type_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_genre_id', 'application', 'genre', ['genre_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_questionnaire_id', 'session', 'questionnaire', ['questionnaire_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_app_id', 'session', 'application', ['app_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_app_id', 'session', type_='foreignkey')
    op.drop_constraint('fk_questionnaire_id', 'session', type_='foreignkey')
    op.drop_constraint('fk_genre_id', 'application', type_='foreignkey')
    op.drop_constraint('fk_type_id', 'application', type_='foreignkey')
    # ### end Alembic commands ###
