"""empty message

Revision ID: f3daeef03f0a
Revises: 2140400898af
Create Date: 2019-04-15 18:05:02.990082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3daeef03f0a'
down_revision = '2140400898af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_app_type_id', 'application', 'application_type', ['app_type_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_genre_id', 'application', 'genre', ['genre_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_genre_id', 'application', type_='foreignkey')
    op.drop_constraint('fk_app_type_id', 'application', type_='foreignkey')
    # ### end Alembic commands ###
